name: lodestar-frontend
development: true

servicePort: 8080

imageName: "lodestar-frontend"
imageTag: "latest"

git:
  uri: https://github.com/rht-labs/lodestar-frontend.git
  ref: master

baseUrl: url
clientId: secret
authBaseUrl: url
backendUrl: url

access:
  groups:
  - name: general
    roles:
    - basic
    - view
  - name: advanced
    roles:
    - admin

e2eTestJob:
  enabled: false
  createSecret: false
  cleanUp:
    image:
      name: quay.io/redhat-cop/gitlab-cleanup
      tag: v3.11.6
  action:
    image:
      name: appropriate/curl
      tag: 3.1
  env:
    logLevel: DEBUG
    deleteAfterInHours: 1
    dryRun: false
